@startuml


skinparam sequence {
	ArrowColor Darkcyan
	ActorBorderColor Darkcyan
	LifeLineBorderColor Darkcyan
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor Darkcyan
	ParticipantBackgroundColor Darkcyan
	ParticipantFontName Roboto
	ParticipantFontSize 17
	ParticipantFontColor white

	ActorBackgroundColor Darkcyan
	ActorFontColor Darkcyan
	ActorFontSize 17
	ActorFontName Roboto

}
skinparam shadowing false
skinparam SequenceGroupBorderColor Darkcyan

actor Cliente

Sistema -> DB : richiesta lista prodotti
activate DB
DB --> Sistema : lista prodotti
deactivate DB

Sistema --> Cliente : invio catalogo
loop
    group "Filtri di ricerca"
        Cliente -> Sistema : inserimento ricerca per nome
        activate Sistema
        Cliente -> Sistema : selezione tipo prodotti
        Cliente -> Sistema : selezione genere
        Cliente -> Sistema : selezione ordinamento dei prodotti
    end

    Sistema -> Sistema : ricalcolo lista dei prodotti
    activate Sistema
    Sistema --> Cliente : invio nuova lista di prodotti
    deactivate Sistema
    deactivate Sistema
end
Cliente -> Sistema : visualizza dettagli prodotto
activate Sistema
Sistema --> Cliente : mostra dettagli
deactivate Sistema





@enduml